### ISSUE TITLE
undefined method `delegate' for NSDictionary:Class

### ISSUE THREAD

**Issue by nickyhajal** [rubymotion/motion-support#41]
Hey guys, I'm on High Sierra running RubyMotion 5.8 and I am hitting this error on build:

```
 Simulate ./wds-ios/build/iPhoneSimulator-8.0-Development/WDS App.app (main)>

2018-05-02 12:03:08.783 WDS App[62727:63049444] vendor/bundle/ruby/2.4.0/gems/motion-support-1.2.0/motion/core_ext/ns_dictionary.rb:11:in `<main>':
undefined method `delegate' for NSDictionary:Class (NoMethodError) 	from vendor/bundle/ruby/2.4.0/gems/motion-support-1.2.0/motion/core_ext/ns_dictionary.rb:11:in `<main>'

2018-05-02 12:03:08.795 WDS App[62727:63049444]*** Terminating app due to uncaught exception 'NoMethodError', reason: 'vendor/bundle/ruby/2.4.0/gems/motion-support-1.2.0/motion/core_ext/ns_dictionary.rb:11:in `<main>': undefined method `delegate' for NSDictionary:Class (NoMethodError) 	from vendor/bundle/ruby/2.4.0/gems/motion-support-1.2.0/motion/core_ext/ns_dictionary.rb:11:in `<main>'
```

Any thoughts? Thanks!

**Comment by amirrajan** [comment]
This is probably related to: https://github.com/rubymotion/motion-support/issues/38

**Comment by wndxlori** [comment]
#38 is fixed.  Upgrade to the most recent version of motion-support.  You may have to uninstall and reinstall motion-support
